name: Check PR

on: [pull_request]

jobs:
  run-ci:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install --force

      - name: Lint
        run: npm run lint

      - name: Check build
        run: npm run build
